# Generated by Django 5.2.7 on 2025-10-26 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('brand', models.CharField(max_length=255)),
                ('alcohol_type', models.CharField(choices=[('Beer', 'Beer'), ('Wine', 'Wine'), ('Liquor', 'Liquor')], max_length=6)),
                ('abv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('v_units', models.CharField(choices=[('mL', 'mL'), ('L', 'L'), ('fl oz', 'fl oz')], max_length=5)),
                ('origin', models.CharField(max_length=255)),
                ('bottler', models.CharField(max_length=255)),
                ('bottler_address', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=50)),
                ('health_warnings', models.CharField(max_length=510)),
            ],
        ),
    ]
